name: mvc
channels:
  - conda-forge
  - defaults
  - esri
dependencies:
  - python=3.12
  - numpy=1.26
  - pandas=2.2
  - pyogrio=0.10
  - shapely=2.0
  - geopandas=1.0
  - arcgis=2.4
  - catboost=1.2
  - xgboost=2.1
  - lightgbm=4.6
  - optuna=4.3
  - scikit-learn=1.6
  - folium=0.14.0
  - shap=0.48
  - streamlit=1.45
  - streamlit_folium=0.25
  - pydantic=2.10
  - scipy==1.15
  - pip
  - pip:
      - -e .
      - matplotlib==3.7
      - gower==0.1
      - torch==2.7.1+cu126
      - netcal==1.3
      - statsmodels==0.14
      - streamlit_shap==1.0
